version: '2.2'

services:
  web:
    image: dixyiadapter/iadapter:latest
    container_name: iadapter_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:4444:4444
    depends_on:
      - db
    command: python ./src/web.py
    volumes:
      - ./data/:/data/
  db:
    image: postgres
    restart: always
    container_name: iadapter_db
    env_file:
      - .env
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  email_adapter:
    image: dixyiadapter/iadapter:latest
    restart: unless-stopped
    container_name: iadapter_email_adapter
    env_file:
      - .env
    command: python ./src/mail_adapter.py
    depends_on:
      - db

networks:
  default:
    external:
      name: autofaq_default
