version: '2.2'

services:
  web:
    image: averniko/iadapter:latest
    container_name: iadapter_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 127.0.0.1:4444:4444
    depends_on:
      - db
    command: python ./src/web.py
    volumes:
      - ./data/:/usr/src/data/
  db:
    image: postgres
    restart: always
    container_name: iadapter_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  email_adapter:
#    restart: unless-stopped
    container_name: iadapter_email_adapter
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./src/mail_adapter.py

networks:
  default:
    external:
      name: autofaq_default