version: '2.2'

services:
  web:
    restart: unless-stopped
    container_name: iadapter_api
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:4444:4444
    depends_on:
      - db
    command: python ./src/main.py
#    command: tail -F anything
    volumes:
      - ./data/:/data/
  db:
    image: postgres
    restart: always
    container_name: iadapter_db
    env_file:
      - .env.dev
    ports:
    - 5432:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  email_adapter:
#    restart: unless-stopped
    container_name: iadapter_email_adapter
    env_file:
      - .env.dev
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./src/main.py
